routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Movie list as homepage
Route::get('/', function(){
	return redirect('movies');
});

// Movie list
Route::resource('/movies', 'MovieController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MovieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $movies = [

        [

        "title" => "The Secret Life of Pets",
        "description" => "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "image" => "http://cdn.movieweb.com/img.teasers.posters/FIqObXLW646Ctz_377_a.jpg",
        "year" => 2001,
        "duration" => 120


        ],

        [

        "title" => "The Hateful Eight",
        "description" => "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "image" => "http://cdn.movieweb.com/img.teasers.posters/FIGhP06utvaYJM_389_a.jpg",
        "year" => 2002,
        "duration" => 120


        ],

        [

        "title" => "Ghostbusters",
        "description" => "30 years after Ghostbusters took the world by storm, the beloved franchise makes its long-awaited return. Director Paul Feig brings his fresh take to the supernatural comedy, joined by some of the funniest actors working today.",
        "image" => "http://cdn.movieweb.com/img.teasers.posters/FInCjpptml82pw_248_a.jpg",
        "year" => 2002,
        "duration" => 120


        ],

        [

        "title" => "Suicide Squad",
        "description" => "It feels good to be bad… Assemble a team of the world’s most dangerous, incarcerated Super Villains, provide them with the most powerful arsenal at the government’s disposal, and send them off on a mission to defeat an enigmatic, insuperable entity. U.S. intelligence officer Amanda Waller has determined only a secretly convened group of disparate, despicable individuals with next to nothing to lose will do. However, once they realize they weren’t picked to succeed but chosen for their patent culpability when they inevitably fail, will the Suicide Squad resolve to die trying, or decide it’s every man for himself?",
        "image" => "http://cdn.movieweb.com/img.teasers.posters/FIs3ZdMwCtOVww_370_a.jpg",
        "year" => 2016,
        "duration" => 90


        ]

    ];

    return view('movies.index', compact('movies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('movies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->title);
        // dd($request->toArray());

        return redirect()->route('movies.index')->with('status', 'Movie added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $movie = 

        [

        "title" => "The Secret Life of Pets",
        "description" => "For one bustling Manhattan apartment building, the real day starts after the folks on two legs leave for work and school. That’s when the pets of every stripe, fur, and feather begin their own nine-to-five routine: hanging out with each other, trading humiliating stories about their owners or auditioning adorable looks to get better snacks. The buildings top dog, Max (voiced by Louis C.K.) a quick witted terrier rescue who’s convinced he sits at the center of his owner’s universe, finds his pampered life rocked when she brings home Duke (Eric Stonestreet)",
        "image" => "http://cdn.movieweb.com/img.teasers.posters/FIqObXLW646Ctz_377_a.jpg",
        "year" => 2001,
        "duration" => 120


        ];

    
    return view('movies.create', compact('movie'));    
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layout/footer.blade.php
</body>
</html>

resources/views/layout/header.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        
    </head>
    

    <body>

    <nav class="navbar navbar-default">
  <div class="container-fluid">
  
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

  
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li class="{{ Route::is('movies.index') ? 'active' : '' }}"><a href="{{ route('movies.index') }}">Movies <span class="sr-only">(current)</span></a></li>

        <li class="{{ Route::is('movies.create') ? 'active' : '' }}"><a href="{{ route('movies.create') }}">Add Movie</a></li>
        
          
    </div>
  </div>
</nav>

resources/views/main.blade.php
<!-- header includas-->
@include("layout.header")

@if(session('status'))
    <div class="alert alert-info">{{session('status')}}</div>
@endif

@yield("content")


 

<!-- footer includas-->
@include("layout.footer")

resources/views/movies/create.blade.php
@extends("main")

@section("content")


<!-- <link rel="stylesheet" type="text/css" href="main.css"> -->
<article>
    <div class="container form-apply">
        <div class="row">
            <div class="col-md-12 ">
            	<!-- <h3></h3> -->
                <form class="form-horizontal" action="{{ route('movies.store') }}" method="POST">
                			{{ csrf_field() }}
					<fieldset>
						<legend>{{ isset($movie) ? 'Edit movie' : 'Add new movie' }}</legend>
							<div class="form-group">
								<label class="col-md-4 control-label" for="textinput">Item title</label>  
								<div class="col-md-4">
								@if(isset($movie))
									<input value="{{ $movie['title'] }}" name="title" type="text" placeholder="" class="form-control input-md">
								@else
									<input name="title" type="text" placeholder="" class="form-control input-md">
								@endif		
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label" for="year">Year</label> 
								<div class="col-md-4">
								@if(isset($movie))
									<input value="{{ $movie['year'] }}" name="year" type="text" placeholder="" class="form-control input-md">
								@else	
									<input name="year" type="text" placeholder="" class="form-control input-md">
								@endif	
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label" for="duration">Duration min.</label> 
								<div class="col-md-4">
								@if(isset($movie))
									<input value="{{ $movie['duration'] }}" name="duration" type="text" placeholder="" class="form-control input-md">
								@else	
									<input name="duration" type="text" placeholder="" class="form-control input-md">
								@endif	
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label" for="description">Description</label>
								<div class="col-md-4">
								@if(isset($movie))                     
									<textarea class="form-control" rows="10" name="description" placeholder="{{ $movie['description'] }}"></textarea>
								@else	
									<textarea class="form-control" name="description"></textarea>
								@endif	
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label" for="image">Image URL</label>
								<div class="col-md-4">
								@if(isset($movie))                     
									<textarea class="form-control" rows="5" name="image" placeholder="{{ $movie['image'] }}"></textarea>
								@else	
									<textarea class="form-control" name="image"></textarea>
								@endif	
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label" for="singlebutton">Add new item to my shop</label>
								<div class="col-md-4">
									<input type="submit" name="save" class="btn btn-inverse"></input>
								</div>
							</div>
					</fieldset>
				</form>
            </div>
        </div>
    </div> <!-- container main -->   
</article> 
@endsection

resources/views/movies/index.blade.php
@extends("main")

@section("content")


<!-- <link rel="stylesheet" type="text/css" href="main.css"> -->

	<div class="container">
	<h3>Movies</h3>
		<div class="row">
			@foreach ($movies as $movie)
				<div id="movies" class="col-md-3 col-sm-12 col-xs-12">
					<div class="movie-images">
						<h3>{{ $movie['title'] }}</h3>
						<img src="{{$movie['image']}}" width="200">
						<div class="movie-images-body">
							<h4>{{ $movie['year'] }}</h4>
							<h5>{{ $movie['duration'] }} mins</h5>
							<h5>{{ $movie['description'] }}</h5>
						</div>
					</div>
				</div>
			@endforeach
		</div>	
	</div>

@endsection